### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by mschipperheyn** [reactioncommerce/reaction-file-collections#5]
Wanted to bring a migration issue to attention. 
```
=> Started proxy.                             
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
=> Started MongoDB.                           
15:43:34.517Z  INFO Reaction: Load default data from /private/data/
15:43:34.613Z  INFO Reaction: JobServer started
15:43:35.389Z  WARN Reaction: Skipped loading settings from reaction.json.
15:43:36.988Z  INFO Reaction: Reaction Version: 1.10.0
15:43:37.030Z  INFO Reaction: Migrating from version 19 -> 24
15:43:37.031Z  INFO Reaction: Running up() on version 20
15:43:37.038Z  INFO Reaction: Running up() on version 21
15:43:37.040Z  INFO Reaction: Running up() on version 22
15:43:37.054Z  INFO Reaction: Running up() on version 23
15:43:37.253Z  INFO Reaction: Running up() on version 24
15:43:37.284Z ERROR Reaction: FileRecord.url: filename is required
  Error: FileRecord.url: filename is required
      at getUrlForFileRecord (/test/reaction/node_modules/@reactioncommerce/file-collections/dist/common/FileRecord/url.js:20:29)
      at FileRecord.url (/test/reaction/node_modules/@reactioncommerce/file-collections/dist/common/FileRecord/FileRecord.js:331:32)
      at mediaArray.map.media (imports/plugins/core/catalog/server/methods/catalog.js:104:25)
      at Array.map (<anonymous>)
      at Promise.asyncApply (imports/plugins/core/catalog/server/methods/catalog.js:102:35)
      at /Users/me/.meteor/packages/promise/.0.10.2.6syjw.dgdz8s++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/Users/me/.meteor/packages/promise/.0.10.2.6syjw.dgdz8s++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/plugins/core/catalog/server/methods/catalog.js:147:20)
      at /Users/me/.meteor/packages/promise/.0.10.2.6syjw.dgdz8s++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by aldeed** [comment]
Thanks @mschipperheyn. This should be investigated but it looks like more of a Reaction-specific implementation issue rather than an issue with this package. Can you close this and open an issue in https://github.com/reactioncommerce/reaction repo instead? Thanks.

**Comment by htmllab** [comment]
1+

**Comment by aldeed** [comment]
Issue moved to [reactioncommerce/reaction #4207](https://github.com/reactioncommerce/reaction/issues/4207) via [**ZenHub**](https://www.zenhub.com/)
